#!/bin/bash -e

# We filter out //line directives because golang/go#27350 affects us in
# Go 1.11.
echo -e "// Code generated by ragel\n// @generated" \
  | cat - parse.go \
  | grep -v "^//line" \
  > tmp
mv tmp parse.go
