// Code generated by thriftrw v1.0.0
// @generated

package integration

import (
	"errors"
	"fmt"
	"go.uber.org/thriftrw/wire"
	"strings"
)

type Foo_Bar_Args struct {
	Arg *int32 `json:"arg,omitempty"`
}

func (v *Foo_Bar_Args) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Arg != nil {
		w, err = wire.NewValueI32(*(v.Arg)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *Foo_Bar_Args) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Arg = &x
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *Foo_Bar_Args) String() string {
	var fields [1]string
	i := 0
	if v.Arg != nil {
		fields[i] = fmt.Sprintf("Arg: %v", *(v.Arg))
		i++
	}
	return fmt.Sprintf("Foo_Bar_Args{%v}", strings.Join(fields[:i], ", "))
}

func (v *Foo_Bar_Args) MethodName() string {
	return "bar"
}

func (v *Foo_Bar_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

var Foo_Bar_Helper = struct {
	Args           func(arg *int32) *Foo_Bar_Args
	IsException    func(error) bool
	WrapResponse   func(int32, error) (*Foo_Bar_Result, error)
	UnwrapResponse func(*Foo_Bar_Result) (int32, error)
}{}

func init() {
	Foo_Bar_Helper.Args = func(arg *int32) *Foo_Bar_Args {
		return &Foo_Bar_Args{Arg: arg}
	}
	Foo_Bar_Helper.IsException = func(err error) bool {
		switch err.(type) {
		case *NotFound:
			return true
		default:
			return false
		}
	}
	Foo_Bar_Helper.WrapResponse = func(success int32, err error) (*Foo_Bar_Result, error) {
		if err == nil {
			return &Foo_Bar_Result{Success: &success}, nil
		}
		switch e := err.(type) {
		case *NotFound:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for Foo_Bar_Result.NotFound")
			}
			return &Foo_Bar_Result{NotFound: e}, nil
		}
		return nil, err
	}
	Foo_Bar_Helper.UnwrapResponse = func(result *Foo_Bar_Result) (success int32, err error) {
		if result.NotFound != nil {
			err = result.NotFound
			return
		}
		if result.Success != nil {
			success = *result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}

type Foo_Bar_Result struct {
	Success  *int32    `json:"success,omitempty"`
	NotFound *NotFound `json:"notFound,omitempty"`
}

func (v *Foo_Bar_Result) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = wire.NewValueI32(*(v.Success)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if v.NotFound != nil {
		w, err = v.NotFound.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("Foo_Bar_Result should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _NotFound_Read(w wire.Value) (*NotFound, error) {
	var v NotFound
	err := v.FromWire(w)
	return &v, err
}

func (v *Foo_Bar_Result) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Success = &x
				if err != nil {
					return err
				}
			}
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.NotFound, err = _NotFound_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if v.NotFound != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("Foo_Bar_Result should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *Foo_Bar_Result) String() string {
	var fields [2]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", *(v.Success))
		i++
	}
	if v.NotFound != nil {
		fields[i] = fmt.Sprintf("NotFound: %v", v.NotFound)
		i++
	}
	return fmt.Sprintf("Foo_Bar_Result{%v}", strings.Join(fields[:i], ", "))
}

func (v *Foo_Bar_Result) MethodName() string {
	return "bar"
}

func (v *Foo_Bar_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
