// Code generated by thriftrw
// @generated

package integration

import (
	"fmt"
	"github.com/thriftrw/thriftrw-go/wire"
	"strings"
)

type NotFound struct{}

func (v *NotFound) ToWire() (wire.Value, error) {
	var (
		fields [0]wire.Field
		i      int = 0
	)
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *NotFound) FromWire(w wire.Value) error {
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		}
	}
	return nil
}

func (v *NotFound) String() string {
	var fields [0]string
	i := 0
	return fmt.Sprintf("NotFound{%v}", strings.Join(fields[:i], ", "))
}

func (v *NotFound) Error() string {
	return v.String()
}
