// Code generated by thriftrw v0.4.0
// @generated

package integration

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("0.4.0", "github.com/yarpc/yab/testdata/yarpc/integration")
}
