package protobuf

import "github.com/jhump/protoreflect/desc"

// DescriptorProvider is a source of protobuf descriptor information. It can be backed by a FileDescriptorSet
// proto (like a file generated by protoc).
// Adapted from https://github.com/fullstorydev/grpcurl
type DescriptorProvider interface {
	// FindSymbol returns a descriptor for the given fully-qualified symbol name.
	FindSymbol(fullyQualifiedName string) (desc.Descriptor, error)

	Close()
}
